CREATE OR REPLACE TRIGGER RIDE_Update_TK
  BEFORE DELETE OR INSERT OR UPDATE ON RIDE_INFO
  FOR EACH ROW
WHEN (new.STATUS ='COMPLETED' OR new.STATUS ='CANCELLED')
BEGIN  
 IF( new.STATUS ='COMPLETED' ) THEN 
    dbms_output.put('RIDE WITH RIDE ID' ||RIDE_ID || 'COMPLETED SUCCESSFULLY');  
 END IF;
 IF( new.STATUS ='CANCELLED' ) THEN 
    dbms_output.put('RIDE WITH RIDE ID' ||RIDE_ID || 'CANCELLED ');  
 END IF;

END;
/
