CREATE TABLE CAR_DETAILS
(   REGISTRATION_NUMBER varchar2(50) not null,
    COLOR varchar2(50),
    MODEL_NUMBER varchar2(50),
    MODEL numeric(10),
    CONSTRAINT CAR_PRIMARY_KEY  PRIMARY KEY (REGISTRATION_NUMBER)
);

