CREATE TABLE LOGIN_INFO--ADD USERID IN FOREIGN KEY IN DRIVER CUSTOMER
(   USER_ID VARCHAR (50) NOT NULL,
    PHONE VARCHAR (20) NOT NULL,
    PASSWORD VARCHAR (50)NOT NULL,
    CONSTRAINT USER_DETAILS_PK  PRIMARY KEY (USER_ID)
);