DROP Table RIDE_RECEIPT

CREATE TABLE RIDE_RECEIPT(
        RECEIPT_ID VARCHAR(20) NOT NULL,--RIDE ID
        TRIP_FARE DECIMAL(10,2),
        --DISCOUNT DECIMAL(10,2) DEFAULT 0.00,
        Tip DECIMAL(10,2) DEFAULT 0.00,
        TOLL_SURCHAGRES_FEES DECIMAL(10,2),
        --TOTAL_FARE DECIMAL(10,2), Displayed in view
        PAYMENT_MODE VARCHAR(10),--CASH,CREDIT CARD,DEBITCARD,WALLET
        TRANSACTION_TIMESTAMP TIMESTAMP WITH LOCAL TIME ZONE,
        TX_DESCRIPTION VARCHAR(20),    
         CONSTRAINT RIDE_REC_PK PRIMARY KEY(RECEIPT_ID)
        
    )