CREATE TABLE UBER_REWARDS
(   CUSTOMER_ID VARCHAR (50) NOT NULL,
    REFRRAL_COUNT INT DEFAULT 0,
    DISCOUNT DECIMAL (10,2) DEFAULT 0.00,--TRIGGER UPDATE
    CONSTRAINT USER_DETAILS_PK  PRIMARY KEY (USER_ID)
);