CREATE TABLE UBER_REWARDS
(   CUSTOMER_ID VARCHAR (50) NOT NULL,
    REFERRAL_COUNTS INT DEFAULT 0,
    DISCOUNT DECIMAL (10,2) DEFAULT 0.00,--TRIGGER UPDATE
    CONSTRAINT UBER_REWARDS_PK  PRIMARY KEY (CUSTOMER_ID)
);