DROP TABLE DRIVER_DETAILS;

CREATE TABLE DRIVER_DETAILS
(   DRIVER_LICENSE_NUMBER VARCHAR(50) NOT NULL,
    REGISTRATION_NUMBER VARCHAR(50),
    DRIVER_NAME VARCHAR(50),
    BEST_QUALITY VARCHAR(50),-- GOOD TALKER,NAVIGATOR,GOOD DRIVING,
    PHONE VARCHAR (10) NOT NULL,
    SHIFT VARCHAR(50) DEFAULT 'DAY',--NIGHT/DAY
    ADDRESS VARCHAR(50),
    CONSTRAINT DRIVER_PK  PRIMARY KEY (DRIVER_LICENSE_NUMBER),
    CONSTRAINT DRIVER_FK FOREIGN KEY (REGISTRATION_NUMBER) REFERENCES CAR_DETAILS(REGISTRATION_NUMBER)  ON DELETE SET NULL
);

