create or replace PROCEDURE UPDATE_RIDES_PR(
	   DL_NUMBER IN DRIVER_DETAILS.DRIVER_LICENSE_NUMBER%TYPE)
IS   
BEGIN
  UPDATE DRIVER_DETAILS SET COMPLETED_RIDES = COMPLETED_RIDES+1 where DRIVER_LICENSE_NUMBER = DL_NUMBER;
  COMMIT;
END;
